[package]
name = "symmetrical-invention"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
base64 = "0.13.0"
flate2 = "1.0.22"
image = "0.23.14"
rqrr = "0.4.0"
